# basic options
title: Argen West
author: Test
description: Test
twitter_username:     r3bl_
github_username:      aleksandar-todorovic
linkedin_username:    aleksandartodorovic


# Build settings
markdown: kramdown
theme: minima
